services:
  # Serviço de backup
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bica-backup
    volumes:
      - ./config/.env:/app/.env
      - ./backup-temp:/backup
      - /mnt/backups:/mnt/backups
    networks:
      - bica-network
    restart: always
    depends_on:
      - postgres

  # Serviço PostgreSQL para testes
  postgres:
    image: postgres:15-alpine
    container_name: bica-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bica
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bica-network
    restart: always

networks:
  bica-network:
    driver: bridge

volumes:
  postgres-data: